secrets:
  tesla.oauth.clientId:
    file: ./secrets/tesla.oauth.clientId
  tesla.oauth.clientSecret:
    file: ./secrets/tesla.oauth.clientSecret
  tesla.oauth.redirectUri:
    file: ./secrets/tesla.oauth.redirectUri

services:
  teslahitch:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    secrets:
      - tesla.oauth.clientId
      - tesla.oauth.clientSecret
      - tesla.oauth.redirectUri
    environment:
      - tesla.config.dir=/config
      - tesla.proxy.url=https://tesla_http_proxy:4443
    volumes:
      - config_data:/config

  tesla_http_proxy:
    image: tesla/vehicle-command:latest
    ports:
      - "4443:4443"
    environment:
      - TESLA_HTTP_PROXY_TLS_CERT=/config/tls-cert.pem
      - TESLA_HTTP_PROXY_TLS_KEY=/config/tls-key.pem
      - TESLA_HTTP_PROXY_HOST=0.0.0.0
      - TESLA_HTTP_PROXY_PORT=4443
      - TESLA_HTTP_PROXY_TIMEOUT=10s
      - TESLA_KEY_FILE=/config/fleet-key.pem
      - TESLA_VERBOSE=true
    volumes:
      - config_data:/config
    depends_on:
      - teslahitch
    restart: unless-stopped

volumes:
  config_data:
